[O, N] = size(label);
labelData = vec2ind(label);
id1=find(labelData==1);
id2=find(labelData==2);
id3=find(labelData==3);
id4=find(labelData==4);
id5=find(labelData==5);
id6=find(labelData==6);
id7=find(labelData==7);
id8=find(labelData==8);
id9=find(labelData==9);
id10=find(labelData==10);
id11=find(labelData==11);
id12=find(labelData==12);
id13=find(labelData==13);
id14=find(labelData==14);
ind0 = 1:N;

% isiData = dataset(1:8,:);
% labelData = dataset(9,:);